name: 'Custom Action'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  command:
    required: false
    description: "Command to run your tests"
  autoTestRun:
    required: false
    description: "Run tests"
  loadPredefiendModule:
    required: false
    description: "Load predefiend module"
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'