on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: bcaglayan/custom-javascript-action@master
        with:
          tags_input_tryer: ${{ github.actor }}
          tags_tryer2: 'abc1'
          tags.tryer1: 'abc2'
          tags_a.tryer1: 'abc3'
          tags_ml: |
            author1: "${{ github.actor }}"
            author2: ${{ github.actor }}
            abc: ttt
