on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: bcaglayan/custom-javascript-action@v20
        with:
          tags_input_tryer: ${{ github.actor }}
